(display "Довгалюк Павло ІПЗ-41. Лаб 2. Варіант 5. Частина 2.\n")

(define (chain acc)
  (define x 1)
  (define old_x 2)
  (define delta_acc 0)
  (define (chain_iter acc)
    (set! x (/ x 2))
    (set! delta_acc (- old_x x))
    (set! old_x x)
    (if (< delta_acc acc)
        0
        (/ 1 (+ 2 (chain_iter acc)))
      )
   )
  (+ 1 (chain_iter acc))
)
(define acc 0.001)
(display "Answer: ")
(chain acc)
(display "\nAccuracy: ")
(display acc)